name: Deploy para servidor via FTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: 108.167.151.63
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./rmfacilities-onepage/
          server-dir: /rmfacilities.com.br/wp-content/themes/rmfacilities-onepage/
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
